runtime: python27
api_version: 1
threadsafe: true
service: default

handlers:

- url: /(home|login|signup)
  static_files: dist/eventCalendar/index.html
  upload: dist/eventCalendar/index.html
  http_headers:
    Access-Control-Allow-Origin: "*"
    
- url: /(.+)
  static_files: dist/eventCalendar/\1
  upload: dist/eventCalendar/(.*)
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /
  static_files: dist/eventCalendar/index.html
  upload: dist/eventCalendar/index.html
  http_headers:
    Access-Control-Allow-Origin: "*"

skip_files:
- e2e/
- node_modules/
- src/
- ^(.*/)?\..*$
- ^(.*/)?.*\.json$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.yaml$
- ^Dockerfile
- ^LICENSE

libraries:
- name: ssl
  version: latest
