runtime: python27
api_version: 1
threadsafe: true
service: default


handlers:
- url: /api/.*
  script: main.app

skip_files:
- ^(.*/)?\..*$
- ^(.*/)?.*\.json$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.yaml$
- ^Dockerfile
- ^LICENSE

libraries:
- name: ssl
  version: latest
