runtime: python27
api_version: 1
threadsafe: true
service: backend


handlers:
- url: /api/.*
  script: main.app
  http_headers:
    Access-Control-Allow-Origin: "*"

skip_files:
- ^(.*/)?\..*$
- ^(.*/)?.*\.json$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.yaml$
- ^Dockerfile
- ^LICENSE

libraries:
- name: ssl
  version: latest
