runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /api/.*
  script: main.app

- url: /home
  static_files: ../frontend/dist/eventCalendar/index.html
  upload: ../frontend/dist/eventCalendar/index.html

- url: /(.+)
  static_files: ../frontend/dist/eventCalendar/\1
  upload: ../frontend/dist/eventCalendar/(.*)

- url: /
  static_files: ../frontend/dist/eventCalendar/index.html
  upload: ../frontend/dist/eventCalendar/index.html

skip_files:
- e2e/
- node_modules/
- src/
- ^(.*/)?\..*$
- ^(.*/)?.*\.json$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.yaml$
- ^Dockerfile
- ^LICENSE

libraries:
- name: ssl
  version: latest
